In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("DateFruit_Dataset.csv")

In [2]:
df.head() #34 features 1 category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [3]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [4]:
df.shape

(898, 35)

In [5]:
X=df.drop("Class",axis=1)

y=df["Class"]

In [9]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [11]:
X_train

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,169573,1548.9830,594.8965,364.4516,0.7904,464.6580,0.9932,170738,0.8245,1.6323,...,-0.6257,2.4879,2.1186,2.4125,-35847098368,-33293408256,-27052677120,69.5829,67.4267,61.7498
270,102142,1223.5020,441.7251,296.5040,0.7412,360.6262,0.9863,103559,0.7847,1.4898,...,-0.5385,3.7325,3.9749,3.0696,-20307597312,-20240594944,-18247018496,68.7153,69.4312,65.9034
860,212397,1773.1410,649.3710,418.6798,0.7644,520.0310,0.9773,217331,0.7605,1.5510,...,0.1680,2.8597,2.8887,3.0498,-21660262400,-16450807808,-15513940992,50.1400,43.9826,43.0455
435,441826,2486.4771,942.0581,603.1290,0.7682,750.0336,0.9948,444138,0.8075,1.5620,...,1.7484,7.9695,9.3755,7.3022,-36332118016,-32863416320,-37779701760,43.0456,41.0627,43.2121
102,212744,1720.3030,628.2148,432.3847,0.7254,520.4556,0.9918,214501,0.7818,1.4529,...,-0.2504,1.9579,2.1380,2.4907,-28291532800,-27781709824,-24325011456,55.4153,54.8434,52.6176

In [12]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [13]:
#ANN
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

In [14]:
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)

X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [15]:
train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [17]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [20]:
#build our model
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__() 
        self.model=nn.Sequential(
            nn.Linear(X.shape[1],64),
            nn.ReLU(),
            nn.Linear(64,64),
            nn.ReLU(),
            nn.Linear(64,7)
        )
    def forward(self,x):
        
        return self.model(x)

In [21]:
model=ANN()
#loss & optim
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [23]:
#training nn
epochs=100
for epoch in range( epochs):
    model.train()
    running_loss=0.0
    for xb,yb in train_loader:
        optimizer.zero_grad() # optimizer acccumulates prev grad values thus set it to 0 for every iteration
        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step()#params update
        running_loss+=loss.item()
    train_loss=running_loss/len(train_loader)
    print(f"epoch={epoch+1}/{epochs},loss={train_loss}")

epoch=1/100,loss=0.020845454317801024
epoch=2/100,loss=0.018965803876357233
epoch=3/100,loss=0.018952191817452727
epoch=4/100,loss=0.024128967324150322
epoch=5/100,loss=0.020659618160646896
epoch=6/100,loss=0.018859615427968296
epoch=7/100,loss=0.018179632672716096
epoch=8/100,loss=0.01819530931179938
epoch=9/100,loss=0.017300594375347315
epoch=10/100,loss=0.017003658263053258
epoch=11/100,loss=0.016244274862718
epoch=12/100,loss=0.01723804028765501
epoch=13/100,loss=0.016118951405034117
epoch=14/100,loss=0.01618355294972982
epoch=15/100,loss=0.017338250368914527
epoch=16/100,loss=0.014815731551093251
epoch=17/100,loss=0.014681938205562208
epoch=18/100,loss=0.01731417928797031
epoch=19/100,loss=0.01467179419958721
epoch=20/100,loss=0.015243841562946529
epoch=21/100,loss=0.013846217472430157
epoch=22/100,loss=0.018731851424293025
epoch=23/100,loss=0.014565947141660296
epoch=24/100,loss=0.013012958328624296
epoch=25/100,loss=0.014857741295481506
epoch=26/100,loss=0.015132139320485294
epoch=27/100,loss=0.01261967297076531
epoch=28/100,loss=0.012666068161311357
epoch=29/100,loss=0.01133687122542735
epoch=30/100,loss=0.014200615570070628
epoch=31/100,loss=0.011788998161057902
epoch=32/100,loss=0.0104825300412536
epoch=33/100,loss=0.011331002443077286
epoch=34/100,loss=0.012886289537519864
epoch=35/100,loss=0.0121945015530598
epoch=36/100,loss=0.009990989448219214
epoch=37/100,loss=0.009130236619334344
epoch=38/100,loss=0.010615786628635682
epoch=39/100,loss=0.010288694458406257
epoch=40/100,loss=0.009118833794554635
epoch=41/100,loss=0.009200503411905273
epoch=42/100,loss=0.008069513509880104
epoch=43/100,loss=0.01145577702719374
epoch=44/100,loss=0.011240301770158112
epoch=45/100,loss=0.011067014673481817
epoch=46/100,loss=0.008351923578985683
epoch=47/100,loss=0.008155632121285991
epoch=48/100,loss=0.007915734809458903
epoch=49/100,loss=0.011186481319189466
epoch=50/100,loss=0.008343399909790605
epoch=51/100,loss=0.00656239757296609
epoch=52/100,loss=0.008055683836573735
epoch=53/100,loss=0.0062577626085840166
epoch=54/100,loss=0.009293592929759103
epoch=55/100,loss=0.00884411120078648
epoch=56/100,loss=0.0069595558275266185
epoch=57/100,loss=0.007598819700828956
epoch=58/100,loss=0.006449929825738882
epoch=59/100,loss=0.005359369218754379
epoch=60/100,loss=0.009703935093610831
epoch=61/100,loss=0.00800211868836018
epoch=62/100,loss=0.015881362006716106
epoch=63/100,loss=0.010707145997161127
epoch=64/100,loss=0.006345498579954121
epoch=65/100,loss=0.007263802131131777
epoch=66/100,loss=0.017125591372504183
epoch=67/100,loss=0.008256101143121234
epoch=68/100,loss=0.007691561654412552
epoch=69/100,loss=0.008533173553903749
epoch=70/100,loss=0.006530969193630406
epoch=71/100,loss=0.007278616251626417
epoch=72/100,loss=0.006327628549669222
epoch=73/100,loss=0.005609104021341013
epoch=74/100,loss=0.004415334206145338
epoch=75/100,loss=0.003991268005768728
epoch=76/100,loss=0.0037613601800884403
epoch=77/100,loss=0.0035169678496616975
epoch=78/100,loss=0.004016034262072619
epoch=79/100,loss=0.0033963764663380775
epoch=80/100,loss=0.004636249167125915
epoch=81/100,loss=0.004095430435288859
epoch=82/100,loss=0.005736443615245187
epoch=83/100,loss=0.004112726004045133
epoch=84/100,loss=0.003140073735266924
epoch=85/100,loss=0.0033781227362139716
epoch=86/100,loss=0.0028484731858992272
epoch=87/100,loss=0.0030316327237929013
epoch=88/100,loss=0.0030670967800846406
epoch=89/100,loss=0.0037123030507127228
epoch=90/100,loss=0.004232335147959099
epoch=91/100,loss=0.005158999967692501
epoch=92/100,loss=0.0036322730118864338
epoch=93/100,loss=0.003300713166422413
epoch=94/100,loss=0.0030180806225752863
epoch=95/100,loss=0.0032398846990912243
epoch=96/100,loss=0.0034578262964951928
epoch=97/100,loss=0.003196534513414878
epoch=98/100,loss=0.003935892476558523
epoch=99/100,loss=0.0029507289234417208
epoch=100/100,loss=0.0020402047109952114

In [29]:
#evaluate
model.eval()
total=0
correct=0
with torch.no_grad():
    for xb,yb in test_loader:
        outputs=model(xb) #[0.2,0.5,1.3,-0.5,...] 7vals
        max_val,predicted=torch.max(outputs,1)
        correct+=(predicted==yb).sum().item()
        total+=yb.size(0) #actual samples in each batch
print("total vals",total)
print("correct vals",correct)
print("accuracy:",correct/total*100)

total vals 180
correct vals 169
accuracy: 93.88888888888889

In [27]:
y_test.shape

(180,)